# import

class ProcessController:
    def __init__(self) -> None: ...

    # ==== NO ARGS ====
    def wait(): ...

    def wait_count(): ...

    def alive_count(): ...

    # ==== YES ARGS ====
    def set_max_proc(n): ...

    def start(tasks_list): ...
